# tasks file for timezone
---
- name: configure /etc/localtime
  file:
    src: /usr/share/zoneinfo/{{ timezone_zone }}
    dest: /etc/localtime
    state: link
    force: yes
  tags: [configuration, timezone]

- name: configure /etc/timezone
  template:
    src: etc/timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  notify: update tzdata
  tags: [configuration, timezone]
