---
# tasks file for timezone
- name: configure /etc/localtime
  copy: src=/usr/share/zoneinfo/{{ timezone_zone }}
        dest=/etc/localtime
        owner=root
        group=root
        mode=0644
  tags: [configuration, timezone]

- name: configure /etc/timezone
  template: dest=/etc/timezone src=timezone.j2
  notify: update tzdata
  tags: [configuration, timezone]
